// Stage data derived from the upstream feichao93/battle-city stage JSONs (MIT — see
// LICENSE-upstream.txt). One character per 8-wu cell, 26 rows per stage; see `stage-format.ts`
// for the legend and the parser.
import type { StageMapSource } from './stage-format';

export const STAGES_1_TO_12: readonly StageMapSource[] = [
  {
    stageNumber: 1,
    terrainRows: [
      '..........................',
      '..........................',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bbSSbb..bb..bb..',
      '..bb..bb..bbSSbb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..........bb..bb..',
      '..bb..bb..........bb..bb..',
      '..........bb..bb..........',
      '..........bb..bb..........',
      'bb..bbbb..........bbbb..bb',
      'SS..bbbb..........bbbb..SS',
      '..........bb..bb..........',
      '..........bbbbbb..........',
      '..bb..bb..bbbbbb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..........bb..bb..',
      '..bb..bb..........bb..bb..',
      '..bb..bb...bbbb...bb..bb..',
      '...........bEEb...........',
      '...........bEEb...........',
    ],
    enemyQueue: 'bbbbbbbbbbbbbbbbbbff',
  },
  {
    stageNumber: 2,
    terrainRows: [
      '......SS......SS..........',
      '......SS......SS..........',
      '..bb..SS......bb..bb..bb..',
      '......SS......bb..bb..bb..',
      '..bb........bbbb..bbSSbb..',
      '..bb........bbbb..bbSSbb..',
      '......bb..........SS......',
      '......bb..........SS......',
      'ff....bb....SS....bbffbbSS',
      'ff....bb....SS....bbffbbSS',
      'ffff......bb....SS..ff....',
      'ffff......bb....SS..ff....',
      '..bbbbbbffffffSS....ffbb..',
      '..bbbbbbffffffSS....ffbb..',
      '......SSffbb..bb..bb..bb..',
      '......SSffbb..bb..bb..bb..',
      'SSbb..SS..bb..bb......bb..',
      'SSbb..SS..bb..bb......bb..',
      '..bb..bb..bbbbbb..bbSSbb..',
      '..bb..bb..bbbbbb..bbSSbb..',
      '..bb..bb..bbbbbb..........',
      '..bb..bb..bbbbbb..........',
      '..bb..............bb..bb..',
      '..bb.......bbbb...bb..bb..',
      '..bb..bb...bEEb...bbbbbb..',
      '..bb..bb...bEEb...bbbbbb..',
    ],
    enemyQueue: 'aaffffbbbbbbbbbbbbbb',
  },
  {
    stageNumber: 3,
    terrainRows: [
      '........bb......bb........',
      '........bb......bb........',
      '..ffffffbb................',
      '..ffffffbb..........SSSSSS',
      'bbffffff..................',
      'bbffffff..................',
      'ffffffff......bb..bbbbbbb.',
      'ffffffff......bb..bbbbbbb.',
      'ffffffffbbbbbbbb..bb...b..',
      'ffffffffbbbbbb....bb...b..',
      'ffffffff....bb.........b..',
      'ffffffff....bb.........b..',
      '..ff........SSSSSS....ff..',
      '..ff........SSSSSS....ff..',
      '......bb..........ffffffff',
      '..bb..bb..........ffffffff',
      'bbb..bbbb...bbbbbbffffffff',
      'bbb..bbbb.bb......ffffffff',
      '..........bb......ffffffff',
      '..........bb..bbbbffffffff',
      'bb....S.......bbbbffffff..',
      'bb....S...........ffffff..',
      'bbbb..S...........ffffff..',
      'bbbb..S....bbbb...ffffff..',
      'SSbbbb.....bEEb...bb......',
      'SSbbbb.....bEEb...bb......',
    ],
    enemyQueue: 'bbbbbbbbbbbbbbffffaa',
  },
  {
    stageNumber: 4,
    terrainRows: [
      '..ffff................ff..',
      '..ffff................ff..',
      'ffff......bbbb..........ff',
      'ffff....bbbbbbbbbb......ff',
      'ff.....bbbbbbbbbbbbb....SS',
      'ff.....bbbbbbbbbbbbbbb....',
      'SS....bbbbbbbbbbbbbbbbb...',
      '......bbbbbbbbbbbbbbbbb...',
      '.....bbb......bbbbbb..b...',
      '.....b..........bbbb..b...',
      '~~...b..S...S...bbb.......',
      '~~...b..S...S...bbb.......',
      '....bb..........bbb...~~~~',
      '....bb..bbbb....bbb...~~~~',
      '....bbbbbbbbbbbbbbbb......',
      '....bbbbbbbbbbbbbbbb......',
      '...bbbbbbbbbbbbbbbbbb.....',
      '...bbbbbbbbbbbbbbbbbb.....',
      '..bbbbbbbbbbbbbbbbbbbb....',
      '......bbbbbbbbbbbb........',
      '..bbbb..bbbbbbbb..bbbb..ff',
      '..bbbbbb..bbbb..bbbbbb..ff',
      'ff..bbbb........bbbb..ffff',
      'ff.........bbbb.......ffff',
      'SSff.......bEEb.....ffffSS',
      'SSff.......bEEb.....ffffSS',
    ],
    enemyQueue: 'ppppppppppfffffbbaaa',
  },
  {
    stageNumber: 5,
    terrainRows: [
      '........bbbb..............',
      '........bbbb..............',
      '........bb......SSSSSS....',
      'SS..bb..bb..........SS....',
      'SS..bb......bb............',
      'SS..bb......bb............',
      'bb..bbbbbb..bbbb..~~~~..~~',
      'bb..bbbbbb..bbbb..~~~~..~~',
      'bb......bb........~~......',
      '..................~~......',
      '........~~~~..~~~~~~..bbbb',
      '....bb..~~~~..~~~~~~..bbbb',
      'bbbb....~~bb..bbbb........',
      'bbbb....~~bb..bbbb........',
      '........~~...........SS...',
      '........~~...........SS...',
      '~~~~~~..~~..SS..bb...S....',
      '~~~~~~..~~..SS..bb...S....',
      '.....................Sbbbb',
      '......bbbb...........Sbbbb',
      '........bbbbbbbbbb........',
      '........bb......bbbb......',
      'bbbbbb............bbbb....',
      'bbbb.......bbbb.....bb....',
      'bb.........bEEb...........',
      '...........bEEb...........',
    ],
    enemyQueue: 'pppppaabbbbbbbbfffff',
  },
  {
    stageNumber: 6,
    terrainRows: [
      '...........b..b.ffff......',
      '...........b..b.ffff......',
      '..b..S..b........bffb..bff',
      '..b..S..b........bffb..bff',
      '..b..S..b...bb...bffb..bff',
      '..b..S..b...bb...bffb..bff',
      '..bb....bb..SS..bbff..bbff',
      '..bb....bb..SS..bbff..bbff',
      '.......bSS..bb..bbS...ffff',
      '.......b....bb....S...ffff',
      'bbbbb.....ffbbff.....bbbbb',
      'bbbbb.....ffbbff.....bbbbb',
      '.........bffffffb.........',
      '.........bffffffb.........',
      'SSbbbb..bbffffffbb.bbbbbSS',
      'SSbbbb....ffffff...bbbbbSS',
      'SSSSSS......ff......SSSSSS',
      '........bb..ff..bb........',
      '..bb....bb......bb........',
      '..bb....bb......bb........',
      '..bbb.....bb..bb.....bbbff',
      '..bbb................bbbff',
      '....bb..............ffffff',
      '...........bbbb.....ffffff',
      '...........bEEb.......ffff',
      '....bb.....bEEb.....bbffff',
    ],
    enemyQueue: 'pppppppffbbbbbbbbbaa',
  },
  {
    stageNumber: 7,
    terrainRows: [
      '..............SSSS........',
      '..........................',
      '....SSSSSSSS........SS....',
      '....SS..............SS....',
      '....SS......ff..SSSSSS....',
      '....SS......ff....SSSS....',
      '..SS......ffSS......SS....',
      '..SS......ffSS......SS....',
      '........ffSSSS......SSSS..',
      '........ffSSSS........SS..',
      '..SS..ffSSSSSS..SS........',
      '..SS..ffSSSSSS..SS........',
      '...S..SSSS......SSSS......',
      '...S..SSSS......SSSS......',
      'S.......SS..SSSSSS.....S..',
      'S.......SS..SSSSSS.....S..',
      '...SSS......SSSSff....SS..',
      '...SSS......SSSSff....SS..',
      '..SS........SSff....SSSS..',
      '..SS........SSff....SSSS..',
      '..SSSSSS....ff....SS......',
      '......SS....ff....SS......',
      '..................SS....SS',
      '...........bbbb.......SSSS',
      '...........bEEb...........',
      'SSSS.......bEEb...........',
    ],
    enemyQueue: 'bbbffffppppppbbbbbbb',
  },
  {
    stageNumber: 8,
    terrainRows: [
      '....bb....bb......bb......',
      '....bb....bb..bb..bb......',
      'ffbbbbbb..bb......bbb.....',
      'ffbbbbbb..bb..SS..bbb.....',
      'ffffff....bb..bb..bb...bb.',
      'ffffff........bb.......bb.',
      'ff~~~~~~~~~~~~~~~~~~~~..~~',
      'ff~~~~~~~~~~~~~~~~~~~~..~~',
      '..bb......................',
      '..bb........bbbb..........',
      '....bb.....bbbbbbbbbbbSSSS',
      '....bb.....bbbbb..bb......',
      'bbbb..bb...bbbbbffbb....bb',
      'bbbb..bb...bbbbbffbbSSSSbb',
      '......SS......ffffffff....',
      '......SS..SS..ffffffff....',
      '~~~~..~~~~~~~~~~..~~~~~~~~',
      '~~~~..~~~~~~~~~~..~~~~~~~~',
      'ffff...b..................',
      'ffff...b....bbbb..........',
      'ffffbb..b......b......bb..',
      'ffffbb..b......b..SSbbbb..',
      'ff..bb..b.........bb..bb..',
      'ffSSbb..b..bbbb.......bb..',
      '...........bEEb.......bb..',
      '...........bEEb...bb......',
    ],
    enemyQueue: 'pppppppaaffffbbbbbbb',
  },
  {
    stageNumber: 9,
    terrainRows: [
      '......bb............ff....',
      '......bb..........SSff....',
      'bb............ff.SSSS...bb',
      'bb..........SSff.SSSS...bb',
      '........ff.SSSS...SSff....',
      '......SSff.SSSS.....ff....',
      '.....SSSS...SSff..........',
      '.....SSSS.....ff..........',
      '......SSff................',
      '........ff................',
      '......ff..ff..ff..ff......',
      '......ffSSff..ffSSff......',
      'SSbb...SSSS....SSSS...bbSS',
      'SSbb...SSSS....SSSS...bbSS',
      '......ffSSff..ffSSff......',
      '......ff..ff..ff..ff......',
      '..........................',
      '........SS......SS........',
      'bb.....SSSS....SSSS.....bb',
      'bb.....SSSS....SSSS.....bb',
      'bb....ffSSff..ffSSff....bb',
      'bb....ff..ff..ff..ff....bb',
      '..........................',
      '....bb.....bbbb.....bb....',
      '....bbbb...bEEb...bbbb....',
      '....bbbb...bEEb...bbbb....',
    ],
    enemyQueue: 'ffffffffffpppppppaaa',
  },
  {
    stageNumber: 10,
    terrainRows: [
      '..........................',
      '..........................',
      '...bbbbb............bbbbb.',
      '...b..bb............bb..b.',
      '.bbb....bb..ffff..bb.....b',
      '.b......bb..ffff..bb.....b',
      'bb......bbffffffffbb.....b',
      'bb......bbffffffffbb.....b',
      'bb......bbffSSSSffbb....bb',
      'bb......bbffSSSSffbb....bb',
      '.b....bb~~~~~~~~~~~~bbbbbb',
      '.bbbbbbb~~~~~~~~~~~~bbbbbb',
      '..bbbbbbSSSSbbSSSSbbbbbbb.',
      '..bbbbbbSSSSbbSSSSbbbbbbb.',
      '....bbbbSS..bb..SSbbbbb...',
      '....bbbbSS..bb..SSbbbbb...',
      '....bbbbbbbbbbbbbbbbbbb...',
      '....bbbbbbbbbbbbbbbbbbb...',
      'bbffbbbbbbSSSSbbbbbbbbffbb',
      'bbff......SSSS........ffbb',
      'bbffffffffffffffffffffffbb',
      'bbffffffffffffffffffffffbb',
      '....ffffff......ffffffff..',
      '....ffffff.bbbb.ffffffff..',
      '......b....bEEb.....b.....',
      '......b....bEEb.....b.....',
    ],
    enemyQueue: 'bbbbbbbbbbbbffppppaa',
  },
  {
    stageNumber: 11,
    terrainRows: [
      '..........SS..bb..bbbb....',
      '..........SS..bb..bbbb....',
      '...bbbbbbbbb..bb..........',
      '...bbbbbbbbb..bb..........',
      '......b...bb..bbbb..ffffff',
      '......b...bb..bbbb..ffffff',
      '...b..........SS..ffffffff',
      '...b..........SS..ffffffff',
      '...b..bbbbbbSSbbbbffffbbSS',
      '...b..bbbbbbSSbbbbffff..SS',
      '..bbbbbbSS....bb..ffff...b',
      '........SS....bb..ffff...b',
      '.bbbbbbb..SSffffffffff....',
      '.bbbbbbb..SSffffffffff....',
      '......SS....ffffffffffbb..',
      '......SS....ffffffffffbb..',
      'SSbb..ffffffffSSffffffbb..',
      'SSbb..ffffffffSSffffffbb..',
      '.bbbffffffffff........bbb.',
      '.bbbffffffffff........bbb.',
      '..bbffff........SSbbbbbb..',
      '..bbffff..........bbbbbb..',
      '....ffff..........bb...b..',
      '....ffff...bbbb...bb...b..',
      '....ffff...bEEb...........',
      '..bbffff...bEEb...........',
    ],
    enemyQueue: 'fffffaaaaaappppfffff',
  },
  {
    stageNumber: 12,
    terrainRows: [
      '..............bbbbbb......',
      '..............bbbbbb......',
      '..bbbbbb..........bb......',
      '..bbbbbbbb..bb....bb......',
      '........bb..bb........bbbb',
      '........bb............bbbb',
      '..~~~~~~~~~~..bbb.....bbSS',
      '..~~~~~~~~~~..bbb.....bb..',
      '..........~~..bb..SSS.bb..',
      '....SSSSSS~~..bb..SSS.bb..',
      'bb..bbbbbb~~~~~~..~~bbbb..',
      'bb..bbbbbb~~~~~~..~~bbbb..',
      '........SS~~......~~SS....',
      '........SS~~......~~......',
      '~~~~~~..~~~~bbbb..~~......',
      '~~~~~~..~~~~bbbb..~~......',
      '..........bbSSSS..~~~~~~..',
      '..........bb......~~~~~~..',
      'bbbbbb....................',
      'bbbbbb....................',
      '....bb..SSSS......bbbb...b',
      '....bb............bbbb...b',
      'bb................bb....bb',
      'bb.........bbbb...bb....bb',
      '...........bEEb...........',
      '...........bEEb...........',
    ],
    enemyQueue: 'ppppppppffffffaaaaaa',
  },
];
