// Stage data derived from the upstream feichao93/battle-city stage JSONs (MIT — see
// LICENSE-upstream.txt). One character per 8-wu cell, 26 rows per stage; see `stage-format.ts`
// for the legend and the parser.
import type { StageMapSource } from './stage-format';

export const STAGES_25_TO_35: readonly StageMapSource[] = [
  {
    stageNumber: 25,
    terrainRows: [
      '......SS..bb..bb..bb..SS..',
      '......SS..bb..bb..bb..SS..',
      '..bb..bb..........SS......',
      '..bb..bb..........SS......',
      '..bb..bb....SS....SS..SSSS',
      '..bb..bb....SS....SS..SSSS',
      '..bb......bb..SSbb......SS',
      '..bb......bb..SSbb......SS',
      '........bbbb..bbbb..SS....',
      '........bbbb..bbbb..SS....',
      '....SS..bb....bbbb..bbbb..',
      '....SS..bb....bbbb..bbbb..',
      'SS..SS....bb..SS....SSbb..',
      'SS..SS....bb..SS....SSbb..',
      '....bbbb..bb......bbSS....',
      '....bbbb..bb......bbSS....',
      '..SSbbbb..bbbb..bbbb....bb',
      '..SSbbbb..bbbb..bbbb....bb',
      '..bb......bbSS........bbbb',
      '..bb......bbSS........bbbb',
      '......bb..bbbbSS..SS....bb',
      '......bb..bbbbSS..SS....bb',
      'bb..bbbb..........bbSS....',
      'bb..bbbb...bbbb...bbSS....',
      'bb..bb.....bEEb...bbbbbb..',
      'bb..bb.....bEEb...bbbbbb..',
    ],
    enemyQueue: 'ppffffffffaaaaaaaaaa',
  },
  {
    stageNumber: 26,
    terrainRows: [
      '....~~~~..................',
      '....~~~~..................',
      '......~~ff..b.............',
      'SS....~~ff..b.............',
      'ff..........S...b...~~~~..',
      'ffSS........S...b...~~~~..',
      'ffff..SS...b....S.ff~~....',
      'ffff....bb.b....S.ff~~....',
      'ffffff....SS...b..........',
      'ffffff....SSbb.b........SS',
      'ffffSS.....b..SS........ff',
      'ffff..SS...b..SSbb....SSff',
      'ffSS....bbSS...b..SS..ffff',
      'ff........SS...b......ffff',
      '..........b.bbSS....ffffff',
      '..........b...SS....ffffff',
      '....~~ff.S....b.bb..SSffff',
      '....~~ff.S....b...SS..ffff',
      '..~~~~...b...S..........ff',
      '..~~~~...b...S..........ff',
      '.............b..ff~~....SS',
      '.............b..ff~~......',
      'SS................~~~~....',
      'SS.........bbbb...~~~~....',
      'SSSS.......bEEb.........SS',
      'SSSS.......bEEb.........SS',
    ],
    enemyQueue: 'ffffffaaaaaabbbbpppp',
  },
  {
    stageNumber: 27,
    terrainRows: [
      '........SS................',
      '........SS................',
      'SSSS....SS....SSSS........',
      'SSSS....SS....SSSS........',
      '..SS....SS......SS..SSSSff',
      '..SS....SS......SS..SSSSff',
      '..SS....SSSSSS..ff..SS....',
      '..SS....SSSSSS..ff..SS....',
      '..bb........SS..SSSSSS....',
      '..bb........SS..SSSSSS....',
      'ffSSSS..SSbbSSbbbb........',
      'ffSSSS..SSbbSSbbbb........',
      '....SSffSSff....bb....SSSS',
      '....SSffSSff....bb....SSSS',
      '....SS....ff....SS....SS..',
      '....SS....ff....SS....SS..',
      '....bb....SS....SSSSbbSS..',
      '....bb....SS....SSSSbbSS..',
      'ffSSSSSSffffbbSSSS..bbSS..',
      'ffSSSSSSffffbbSSSS..bbSS..',
      '......bb........ffff..bb..',
      '......bb........ffff..bb..',
      '......SS..........ff..bb..',
      '......SS...bbbb...ff..bb..',
      '......SS...bEEb...SS..bb..',
      '......SS...bEEb...SS..bb..',
    ],
    enemyQueue: 'ppaaaaaaaaffffffffbb',
  },
  {
    stageNumber: 28,
    terrainRows: [
      '.....................SS...',
      '.....................SS...',
      '....................SS....',
      '............SS......SS....',
      '............ff....bbb.....',
      '..........bbffbb..bbb.....',
      '..........ffffff..bbb.....',
      '........SSffffffSSbbb.....',
      '........ffffiiffffbbb.....',
      '......bbffffiiffffbbb.....',
      '......ffffiiiiiiffffb.....',
      '....SSffffiiiiiiffffb.....',
      '....ffffiiiiiiiiiiffff....',
      '..bbffffiiiiiiiiiiffffbb..',
      '..ffffiiiiiiiiiiiiiiffff..',
      'SSffffiiiiiiiiiiiiiiffffSS',
      'ffffiiiiiiiiiiiiiiiiiiffff',
      'ffffiiiiiiiiiiiiiiiiiiffff',
      '..ffiiiiiiiiiiiiiiiiiiff..',
      '..ffiiiiiiiiiiiiiiiiiiff..',
      '..ffiiiiiiiiiiiiiiiiiiff..',
      '..ffiiiiiiiiiiiiiiiiiiff..',
      '..ffiiiiii......iiiiiiff..',
      '..ffiiiiii.bbbb.iiiiiiff..',
      '..ffiiii...bEEb...iiiiff..',
      '..ffiiii...bEEb...iiiiff..',
    ],
    enemyQueue: 'ffabbbbbbbbbbbbbbbpp',
  },
  {
    stageNumber: 29,
    terrainRows: [
      '....................bb....',
      '....................bb....',
      '..bb~~~~..SS..bb..........',
      '..bb~~~~..SS..bb..........',
      '....~~~~bbffffff~~~~..SS..',
      '....~~~~bbffffff~~~~..SS..',
      '..........ffffff~~~~bb....',
      '..........ffffff~~~~bb....',
      '..SS....~~~~..ff..........',
      '..SS....~~~~..ff..........',
      'ffffbb..~~~~SS........bb..',
      'ffffbb..~~~~SS........bb..',
      'ffffff............SS....SS',
      'ffffff............SS....SS',
      '..bb~~~~..bb..............',
      '..bb~~~~..bb..............',
      'SS..~~~~ffff~~~~ffff..bb..',
      'SS..~~~~ffff~~~~ffff..bb..',
      '........ff..~~~~ffff~~~~..',
      '........ff..~~~~ffff~~~~..',
      '......SSff......ffff~~~~..',
      '......SSff......ffff~~~~..',
      '....bb..bb................',
      '....bb..bb.bbbb...........',
      'bb.........bEEb...bbSS....',
      'bb.........bEEb...bbSS....',
    ],
    enemyQueue: 'ppppppppppffffaaaaaa',
  },
  {
    stageNumber: 30,
    terrainRows: [
      '..........................',
      '..........................',
      '..........................',
      '..........bbbb......SS....',
      '..........ffff......ff....',
      '..SSSS..bbffffSS..bbffbb..',
      '..ffff..ffffffff..ffffff..',
      'bbffffbbffffffffbbffffffbb',
      'ffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffff',
      'SSff~~ffffffffff~~ffffffff',
      'SSff~~ffffffffff~~ffffffff',
      'ffff~~~~~~ffffff~~~~~~ffSS',
      'ffff~~~~~~ffffff~~~~~~ffSS',
      'ffffffff~~ffSSffffff~~ffff',
      'ffffffff~~ffSSffffff~~ffff',
      'ffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffff',
      'ffffffffffbbbbffffffffffSS',
      'ffffffffff....ffffffffff..',
      'SSffffffbb....bbffffffSS..',
      '..ffffff........ffffff....',
      '..SSbbbb........bbbbbb....',
      '...........bbbb...........',
      '...........bEEb...........',
      '...........bEEb...........',
    ],
    enemyQueue: 'bbbbffffffffppppaaaa',
  },
  {
    stageNumber: 31,
    terrainRows: [
      '......~~........~~........',
      '......~~........~~........',
      '~~~~..~~..~~~~~~~~..~~~~~~',
      '~~~~..~~..~~~~~~~~..~~~~~~',
      'ffffbb....bb....~~..~~ff~~',
      'ffffbb....bb....~~..~~ff~~',
      'ff~~~~~~~~..SS....bbffffff',
      'ff~~~~~~~~..SS....bbffffff',
      'ffff..~~....~~..~~~~~~~~ff',
      'ffff..~~....~~..~~~~~~~~ff',
      '~~~~..~~..~~~~....~~......',
      '~~~~..~~..~~~~....~~......',
      '....bbffbb..bbff..~~....~~',
      '....bbffbb..bbff..~~....~~',
      '..~~~~ff~~~~~~~~..ffbb..~~',
      '..~~~~ff~~~~~~~~..ffbb..~~',
      'bb....bb....~~..ffff~~..~~',
      'bb....bb....~~..ffff~~..~~',
      '~~~~..~~~~..~~bb~~~~~~....',
      '~~~~..~~~~..~~bb~~~~~~....',
      '....bb..ffff....ff~~....~~',
      '....bb..ffff....ff~~....~~',
      '..~~~~~~ff........~~..~~~~',
      '..~~~~~~ff.bbbb...~~..~~~~',
      '..~~.......bEEb...........',
      '..~~.......bEEb...........',
    ],
    enemyQueue: 'pppffffffffaaaaaappp',
  },
  {
    stageNumber: 32,
    terrainRows: [
      'iiiiiiiiiiii..iiiiiiiiiiii',
      'iiiiiiiiiiii..iiiiiiiiiiii',
      'iiiiiiiiiiiiiiiiiiiiiiiiii',
      'iiiiiiiiiiiiiiiiiiiiiiiiii',
      'iiiiiibbiiiiiiiiiibbiiiiii',
      'iiiiiibbiiiiiiiiiibbiiiiii',
      'iibb..bb..bbiibb..bb..bbii',
      'iibb..bb..bbiibb..bb..bbii',
      'iibbbbbb..........bbbbbbii',
      'ii....bb..........bb....ii',
      'iiiiiibb..bbSSbb..bbiiiiii',
      'iiiiiibbbbbbSSbbbbbbiiiiii',
      'SSiiiiii..SS..SS..iiiiiiSS',
      'SSiiiiii..........iiiiiiSS',
      'iiiiiiii..........iiiiiiii',
      'iiiiiiii..bb..bb..iiiiiiii',
      'iiiiiiii..bb..bb..iiiiiiii',
      'iiiiiiii..bb..bb..iiiiiiii',
      'iiiiiibb..........bbiiiiii',
      'iiiiiibb....bb....bbiiiiii',
      'iibbiibb..SSSSSS..bbiibbii',
      'iibbiibb..........bbiibbii',
      '..bb..bb..........bb..bb..',
      '..bbbbbb...bbbb...bbbbbb..',
      '..bb.......bEEb.......bb..',
      '...........bEEb...........',
    ],
    enemyQueue: 'aaaaaaaabbbbbbppffff',
  },
  {
    stageNumber: 33,
    terrainRows: [
      '........SS........SS......',
      '........SS........SS......',
      '..SS......SS....SSffff....',
      '..SS......SS....SSffff....',
      '....SS........SSff..S.....',
      '....SS........SSffSSS.....',
      '......SS..ffffffffff...S..',
      '......SS..ffffffffff...S..',
      '..S.....SSffffSSff....SS..',
      '..S.....SSffffSSff....SS..',
      '..SSS.ff..SSffffSS.....S..',
      '....S.ff..SSffffSS.....S..',
      '....ffffffffff....SS......',
      '....ffffffffff....SS......',
      '....S.ff..SSff......SS....',
      '..SSS.ff..SSff......SS....',
      '..ffffffSS..SS........SS..',
      '..ffffffSS..SS..SS....SS..',
      'ffffffSS.........S........',
      'ffffffSS.........S........',
      '....SS.................SSS',
      '....SS.................SSS',
      '....................S.....',
      '...........bbbb...SSS.....',
      'S..........bEEb...........',
      'S...SS.....bEEb...........',
    ],
    enemyQueue: 'ffffaaaaaaaappppffff',
  },
  {
    stageNumber: 34,
    terrainRows: [
      '........b..b..............',
      '........b..b..............',
      'b.b.b..b..b.....b.b.......',
      'b.b.b..b..b.....b.b.......',
      'b.b.b.bbbb......b.bbb.....',
      'b.b.b.bbbb......b.bbb.....',
      '.b.b..bbb......bb.bbbb....',
      '.b.b..bbb......bb.bbbb....',
      '..b...bb.bb...b.bbbbbb....',
      '..b...bb.bb...b.bbbbbb....',
      '..b..b....bbb.bb.b.bbb....',
      '..b..b....bbb.bb.b.bbb....',
      '..b......bbbbbb...b.bb....',
      '..b......bbbbbb...b.bb....',
      '...b....b.bbbbb...b.bb....',
      '...b....b.bbbbb...b.bb....',
      '...bbbbb..bbbbbb..b.b.bbbb',
      '...b......bbbbbb..b.b...bb',
      '...b.....bb.bb.bb.b.b..b.b',
      '...b.....bb.bb.bb.b.b..b.b',
      '....b...bb.bb.bbbb.....b..',
      '....b...bb.bb.bbbb.....b..',
      '....b..bb.......bbb...b...',
      '....b..bb..bbbb.bbb...b...',
      '....b..b...bEEb...bbbb....',
      '....b..b...bEEb...bbbb....',
    ],
    enemyQueue: 'ppppffffffffffaaaaaa',
  },
  {
    stageNumber: 35,
    terrainRows: [
      '..........................',
      '..........................',
      '........bb..bb............',
      '........bb..bb............',
      'ff....ffbbffbbff....ff....',
      'ff....ffbbffbbff....ff....',
      'bbffffbbbbbbbbbbffffbbff..',
      'bbffffbbbbbbbbbbffffbbff..',
      'bbbbbbbbSSbbSSbbbbbbbbff..',
      'bbbbbbbbSSbbSSbbbbbbbbff..',
      '~~~~~~bbbbbbbbbb~~~~~~ff..',
      '~~~~~~bbbbbbbbbb~~~~~~ff..',
      '~~bbbbbbbbbbbbbbbbbb~~~~ff',
      '~~bbbbbbbbbbbbbbbbbb~~~~ff',
      'bbbbbb~~bbbbbb~~bbbbbbffff',
      'bbbbbb~~bbbbbb~~bbbbbbffff',
      'bbbb~~~~~~bb~~~~~~bbbb~~~~',
      'bbbb~~~~~~bb~~~~~~bbbb~~~~',
      'ff~~~~ffffffffff~~~~ff~~ff',
      'ff~~~~ffffffffff~~~~ff~~ff',
      '..ffff..........ffff..ff..',
      '..ffff..........ffff..ff..',
      '..........................',
      '...........bbbb...........',
      '...........bEEb...........',
      '...........bEEb...........',
    ],
    enemyQueue: 'ppppffffffaaaaaaaaaa',
  },
];
