// Stage data derived from the upstream feichao93/battle-city stage JSONs (MIT — see
// LICENSE-upstream.txt). One character per 8-wu cell, 26 rows per stage; see `stage-format.ts`
// for the legend and the parser.
import type { StageMapSource } from './stage-format';

export const STAGES_13_TO_24: readonly StageMapSource[] = [
  {
    stageNumber: 13,
    terrainRows: [
      '..........................',
      '........bb......bb........',
      '..bbbbbbbb......bbbbbbbb..',
      '..bbbbbbbb......bbbbbbbb..',
      '..bb........bb........SS..',
      '..bb........bb........SS..',
      '..SS..bbbb......bbbb..bbbb',
      '..SS..bb..........bb..bbbb',
      '..bb..b.ff..SS..ff.b..SSbb',
      '..bb..b.ffSSSSSSff.b..SSbb',
      '..bb....ffffffffff....SSbb',
      '........ffffffffff......bb',
      'bb......ffffffffff......bb',
      'bbSS....ffffffffff....bbbb',
      'bbSS..b.ffSSSSSSff.b..bb..',
      'bbSS..b.ff..SS..ff.b..bb..',
      'bbbb..bb..........bb..SS..',
      'bbbb..bbbb......bbbb..SS..',
      'bbSS........bb........bb..',
      'bbSS........bb........bb..',
      'bbbbbbbbbb......bbbbbbSSSS',
      'bbbbbbbbbb......bbbbbbSSSS',
      'bbbb....bb......bb....bb..',
      'bbbb.......bbbb.......bb..',
      'bbbb.......bEEb...........',
      'bbbb.......bEEb...........',
    ],
    enemyQueue: 'ppppppppffffffffaaaa',
  },
  {
    stageNumber: 14,
    terrainRows: [
      '..........................',
      '..........................',
      'ffff......bbbbbb......ffff',
      'ffff....bbbbbbbbbb....ffff',
      'ff.....bbbbbbbbbbbb.....ff',
      'ff.....bbbbbbbbbbbb.....ff',
      '......bbbbffbbffbbbb......',
      '......bbbbffbbffbbbb......',
      '......bbffffbbffffbb......',
      '......bbffffbbffffbb......',
      'ff....bbbbbbbbbbbbbb....ff',
      'ff....bbbbbbbbbbbbbb....ff',
      'ffff....bbffbbffbb....ffff',
      'ffff....bbffbbffbb....ffff',
      '~~~~~~..bbbbbbbbbb..~~~~~~',
      '~~~~~~..bbbbbbbbbb..~~~~~~',
      '.........b.b.b.b.b........',
      '.........b.b.b.b.b........',
      '........b.b.b.b.b.........',
      '........b.b.b.b.b.........',
      '.S.S.S..............S.S.S.',
      '.S.S.S..............S.S.S.',
      'b.b.b................b.b.b',
      'b.b.b......bbbb......b.b.b',
      'S.S.S..S...bEEb...S..S.S.S',
      'S.S.S..S...bEEb...S..S.S.S',
    ],
    enemyQueue: 'ppppppppppffffaaaaaa',
  },
  {
    stageNumber: 15,
    terrainRows: [
      '........bbbb....bb........',
      '........bbbb....bb........',
      '..ffffbbbb......bb........',
      '..ffffbbbb......bb........',
      'ffffffffffffffffbbbb......',
      'ffffffffffffffffbbbb......',
      'ffSSbbffbbbbbbffffffffbbSS',
      'ff..bbffbbbbbbffffffffbbSS',
      'ffffbbffffffSSffffbbS.bb..',
      'ffffbbffffff..ffffbbS.bb..',
      '..ffffbb..ffffffffbb..bb..',
      '..ffffbbSSffffffffbb..bb..',
      '..bbbbbbbbbbffffbbbbb.ffff',
      '..bbbbbbbbbbffffbbbbb.ffff',
      '.SSSbbbb......bbbb......ff',
      '.S..bbbb......bb........ff',
      '..bb..bb......bbffffbbb.ff',
      '..bb..bb..SSbb..ffffbbb.ff',
      '..bb.....bbbbbffffbb....ff',
      '..bb.....bbb..ffffbb....ff',
      '..bbbbb..bbbffff..ffbbffff',
      '..bbbbb..b..ffffbbffbbffff',
      '....bb..ff......bbffbbff..',
      '....bb..ff.bbbb.bbff..ff..',
      '....bb.....bEEb...ffffff..',
      '...........bEEb...ffffff..',
    ],
    enemyQueue: 'bbffffffffffaaaaaaaa',
  },
  {
    stageNumber: 16,
    terrainRows: [
      '..........................',
      '..........................',
      '....SSffSS................',
      '....SSffSS................',
      '......ff..ff..............',
      '......ff..ffSS............',
      '..ff........ff............',
      '..ff........ffbb..........',
      '..ffff....ff..ff..........',
      '..ffff....ff..ffSS........',
      '..ff..ff..ff....ff........',
      '..ff..ff..ff....ffbb......',
      '..ff....ff......ffff......',
      '..ff....ff......ffffSS....',
      '....ff........ffffffff....',
      '....ff........ffffffffbb..',
      '......ff....ff..ffffffff..',
      '......ff....ff..ffffffff..',
      'bb..........ff....ffffffSS',
      'bb..........ff....ffffffSS',
      'bbbb..........ff..ffffffff',
      'bbbb..........ff..ffffffff',
      'SSbbbb..........ff..ffffff',
      'SSbbbb.....bbbb.ff..ffffff',
      'SSSSbbbb...bEEb.ff....ffff',
      'SSSSbbbb...bEEb.ff....ffff',
    ],
    enemyQueue: 'bbbbbbbbbbbbbbbbffaa',
  },
  {
    stageNumber: 17,
    terrainRows: [
      '..........................',
      '........bb..........bb....',
      '..bb..bbbb....iiiiiibbbb..',
      '..bb..bbbb....iiiiiibbbb..',
      '..bb....bb..SSiiiiiiiiii..',
      '..bb....bb..SSiiiiiiiiii..',
      'iiiiiiS.bb....bbiiiiiiii..',
      'iiiiiiS.bb....bbiiiiiiii..',
      'iiiiiiiiiiiibbbb.bb.......',
      'iiiiiiiiiiiibbbb.bb.......',
      '.....Siiiiiiiibb.bb...SSSS',
      '.....Siiiiiiiibb.bb.......',
      'bbbbbbbbiiiiiiiiiiiiiibbbb',
      'bbbbbbbbiiiiiiiiiiiiiibbbb',
      '......bbbbiiiiiiiiS.......',
      '......bbbbiiiiiiiiS.......',
      '..bbbbbb..iiiiiibbbb..bb..',
      '..bbbbbb..iiiiiibbbb..bb..',
      'iiiiiibbii........bb..bb..',
      'iiiiiibbii........bb..bb..',
      'iiiiiiiiiiSS..SS......bb..',
      'iiiiiiiiii..........bbbb..',
      'bbiiiiiiii........bb......',
      'bbiiiiiiii.bbbb...bb......',
      'bbbbS......bEEb...bb..bb..',
      'bbbbS......bEEb...bb..bb..',
    ],
    enemyQueue: 'aaffaaaaaaaabbbbbbbb',
  },
  {
    stageNumber: 18,
    terrainRows: [
      '................SSSSSSff..',
      '................SSSSSSff..',
      '..bb............SS....SS..',
      '..bb............SS....SS..',
      'bbffbb......bbbbbbbb..SS..',
      'bbffbb......bbbbbbbb..SS..',
      '..bbffbb....bb..ffbbSSSS..',
      '..bbffbb....bb..ffbbSSSS..',
      '....bb..ffSSbbff..bb......',
      '....bb..ffSSbbff..bb......',
      '........SS..bbSSbbbb......',
      '........SS..bbSSbbbb......',
      '....bbbbSSbb..SS..........',
      '....bbbbSSbb..SS..........',
      '....bb..ffbbSSff..........',
      '....bb..ffbbSSff..........',
      'SSSSSSff..bb....bbbb......',
      'SSSSSSff..bb....bbbb......',
      'SS..bbbbbbbb....bbSSSS....',
      'SS..bbbbbbbb....bbSSSS....',
      'SS....SS..........SSbbbb..',
      'SS....SS..........SSbbbb..',
      'ffSSSSSS............bbSSSS',
      'ffSSSSSS...bbbb.....bbSSSS',
      '...........bEEb.......SSSS',
      '...........bEEb.......SSSS',
    ],
    enemyQueue: 'aaaabbppppppffffffff',
  },
  {
    stageNumber: 19,
    terrainRows: [
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..bb..bb..bb..bb..bb..bb..',
      '..SS..SS..SS..SS..SS..SS..',
      '..........................',
      '........bb......bb........',
      'bb..bb..bb......bb..bb..bb',
      'bb..bbbbbb..bb..bbbbbb..bb',
      'bb..bb..bb..bb..bb..bb..bb',
      'SS..SS..SS..SS..SS..SS..SS',
      '........SS......SS........',
      'ffff....bb..ff..bb....ffff',
      'ffff....bb..ff..bb....ffff',
      'ffffffffbbbbffbbbbffffffff',
      'ffffffffbb..ff..bbffffffff',
      'ffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffff',
      '........bbffffffbb........',
      'bb..bb..bbffffffbb..bb..bb',
      '..bb..bb....ff....bb..bb..',
      '..bb..bb....ff....bb..bb..',
      '..bb..bb..........bb..bb..',
      '..bb..bb...bbbb...bb..bb..',
      '..bb..bb...bEEb...bb..bb..',
      '...........bEEb...........',
    ],
    enemyQueue: 'ffffaaaaaaaabbbbpppp',
  },
  {
    stageNumber: 20,
    terrainRows: [
      '......~~..bb....bb..bb....',
      '......~~..bb....bb..bb....',
      '................bb..SS....',
      '................bb..SS....',
      '......~~....SS..bb..bb....',
      '......~~..bbSS..bb..bb....',
      'SS..bb~~..SS....bb..bb....',
      '....bb~~..SS..bb....bb....',
      '....bb~~......bb..........',
      '....bb~~......bb..........',
      'bb..bb~~~~..~~~~~~~~....bb',
      'bb..bb~~~~..~~~~~~~~....bb',
      '..............ff..~~..SSSS',
      '......bb......ff..~~......',
      'bbbb.bbb..SSffffff~~......',
      'bbbb.bbb..SSffffff~~..bbbb',
      'bb...b....bbffffff~~..bb..',
      '.....b....bbffffff~~..bb..',
      '..........bb..ff..~~..ff..',
      '..SS......bb..ff..~~..ff..',
      '..bb......bbbbbb....ffffff',
      '..bb..SS............ffffff',
      '..bb..bb..........~~ffffff',
      '..bb..bb...bbbb...~~ffffff',
      '...........bEEb...~~..ff..',
      '...........bEEb...~~..ff..',
    ],
    enemyQueue: 'ffffffffbbppaaaaaaaa',
  },
  {
    stageNumber: 21,
    terrainRows: [
      '..........................',
      '......bbbbbb....bb........',
      '....bbbbbbbbbbbbbbbb......',
      '..bbbbbbbbbbbbbbbbbb......',
      '..ffffffffffffffffbbbb....',
      '..ffffffffffffffffbbbb....',
      'ffff............ffffbbbb..',
      'ffff............ffffbbbb..',
      'ff..SS....SS......ffffff..',
      'ff..SS....SS......ffffff..',
      'ff..SS....SS......ffffff..',
      'ff..SS....SS......ffffff..',
      'ff....ff........ffffbbbbb.',
      'ff....ff........ffffbbbbb.',
      'ffffffffffffffffffbbbbbbb.',
      'ffffffffffffffffffbbbbbbb.',
      'bbffffbbbbffffffbbbbbbbb..',
      'bbffffbbbbffffffbbbbbbbb..',
      '..bbbbbbbbbbbbbbbbbbbb..SS',
      '..bbbbbbbbbbbbbbbbbbbb..SS',
      'SS..bbSSbbbbbbbbbbbbb...SS',
      'SS..bbSSbbbbbbbbbbbbb...SS',
      '..SSbbbbSS......bbbbSSSSSS',
      '..SSbb..SS.bbbb.bbbbSSSSSS',
      '...........bEEb...........',
      '...........bEEb...........',
    ],
    enemyQueue: 'ppppppppffbbbbbbaaaa',
  },
  {
    stageNumber: 22,
    terrainRows: [
      '..........ff..............',
      '..........ff..............',
      '........ffSSff............',
      '........ffSSff............',
      '....ff....ff....ffff......',
      '....ff....ff....ffff......',
      '..ffbbff......ffbbbbff....',
      '..ffbbff......ffbbbbff....',
      '....ffbbff......ffff....ff',
      '....ffbbff......ffff....ff',
      'ff....ff....ff........ffSS',
      'ff....ff....ff........ffSS',
      'bbff......ffSSff....ff..ff',
      'bbff......ffSSff....ff..ff',
      'SSbbff......ff....ffSSff..',
      'SSbbff......ff....ffSSff..',
      'bbff....ff......ff..ff....',
      'bbff....ff......ff..ff....',
      'ff....ffbbff..ffbbff......',
      'ff....ffbbff..ffbbff......',
      '......ffbbff....ff....ff..',
      '......ffbbff....ff....ff..',
      '..ff....ff..........ffSSff',
      '..ff....ff.bbbb.....ffSSff',
      'ffSSff.....bEEb...ffbbff..',
      'ffSSff.....bEEb...ffbbff..',
    ],
    enemyQueue: 'ffffffffbbbbbbppaaaa',
  },
  {
    stageNumber: 23,
    terrainRows: [
      '..........................',
      '..........................',
      '..........SSSS............',
      '..........SSSS............',
      '............SS............',
      '............SS............',
      '..SSSSffffbbSSbbffffSSSS..',
      '..SSSSffffbbSSbbffffSSSS..',
      '......SSffffSSffffSS......',
      '......SSffffSSffffSS......',
      'ff......SSffffffSS......ff',
      'ff......SSffffffSS......ff',
      'SSff......ffffff......ffSS',
      'SSff......ffffff......ffSS',
      'ff........SSffSS........ff',
      'ff......SS..ff..SS......ff',
      '........SS......SS........',
      '........SS..SS..SS........',
      '......SS....SS....SS......',
      '......SS....SS....SS......',
      '..........................',
      '..........................',
      '..........................',
      '...........bbbb...........',
      '....SS.....bEEb.....SS....',
      '....SS.....bEEb.....SS....',
    ],
    enemyQueue: 'aaaaaappppffffffffff',
  },
  {
    stageNumber: 24,
    terrainRows: [
      '....SS..bbSS.........b....',
      '....SS..bb...........b....',
      '....bb..bbff..bbbbbbbb....',
      '....bb..bbff....bbbbbb....',
      '..ffff..bbff.bb.......SSSS',
      '..ffff..bbff.bb.......SSSS',
      'ffffffffffffbbbbbb...bbb..',
      'ffffffffffffbbbbbb...bbb..',
      '....ffff....SSbb...bbbbb.b',
      '....ffffbbbb..bb...bbb...b',
      'bbSS....bbbb......bbbb...b',
      'bb....bb..........bb.....b',
      '.b....bbiiiiiiiiiiiiiiiiii',
      '.b..bbbbiiiiiiiiiiiiiiiiii',
      '.b..bb..iiiiiiiiiiiiiiiiii',
      '.b......iiiiiiiiiiiiiiiiii',
      '....SS..iiiiiiiiiiiiiiiiii',
      '....SS..iiiiiiiiiiiiiiiiii',
      'bb..bb..iiiiiiiiiiiiiiiiii',
      'bb..bb..iiiiiiiiiiiiiiiiii',
      '.b..bb..iiiiiiiiiiiiiiiiii',
      '.b..bb..iiiiiiiiiiiiiiiiii',
      '.b..bb..........iiiiiiiiii',
      '.b..bb.....bbbb.iiiiiiiiii',
      '....bb.....bEEb...iiiiiiii',
      '...........bEEb...iiiiiiii',
    ],
    enemyQueue: 'ppppaaffffbbbbbbbbbb',
  },
];
