#!/usr/bin/env bash
# render-oauth-secrets.sh — install /etc/communication/oauth-secrets, the
# 0600-mode EnvironmentFile that holds OAuth client_secret values
# (Yandex today, more providers tomorrow). Skipped when no provider
# requires a secret — the systemd unit then references a non-existent
# file as `EnvironmentFile=-` (the leading dash makes systemd treat the
# file as optional).
#
# Mirrors the pattern in `generate-turn-secret.sh`: secrets stay in a
# 0600 file owned by `communication`, never rendered into the unit
# file or the TOML config.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/common.sh
source "${SCRIPT_DIR}/../../lib/common.sh"

OAUTH_SECRETS_FILE="/etc/communication/oauth-secrets"
OAUTH_PUBLIC_FILE="/etc/communication/oauth-public-ids"

mkdir -p /etc/communication

# Public client ids used to live in the systemd unit; with the unit gone
# they need a file of their own for the container env_file.
require_env GOOGLE_OAUTH_CLIENT_ID
info "Rendering ${OAUTH_PUBLIC_FILE}"
{
  printf 'GOOGLE_OAUTH_CLIENT_ID=%s\n' "${GOOGLE_OAUTH_CLIENT_ID}"
  if [[ -n "${YANDEX_OAUTH_CLIENT_ID:-}" ]]; then
    printf 'YANDEX_OAUTH_CLIENT_ID=%s\n' "${YANDEX_OAUTH_CLIENT_ID}"
  fi
} > "${OAUTH_PUBLIC_FILE}"
chmod 644 "${OAUTH_PUBLIC_FILE}"
ok "Wrote ${OAUTH_PUBLIC_FILE}"


if [[ -z "${YANDEX_OAUTH_CLIENT_SECRET:-}" ]]; then
  if [[ -f "${OAUTH_SECRETS_FILE}" ]]; then
    rm -f "${OAUTH_SECRETS_FILE}"
    ok "Removed ${OAUTH_SECRETS_FILE} (no OAuth secrets to persist)"
  else
    ok "No OAuth client secrets configured — skipping ${OAUTH_SECRETS_FILE}"
  fi
  exit 0
fi

info "Rendering ${OAUTH_SECRETS_FILE}"
{
  printf '# Generated by render-oauth-secrets.sh — do not commit.\n'
  printf 'YANDEX_OAUTH_CLIENT_SECRET=%s\n' "${YANDEX_OAUTH_CLIENT_SECRET}"
} > "${OAUTH_SECRETS_FILE}"
chmod 600 "${OAUTH_SECRETS_FILE}"
ok "Wrote ${OAUTH_SECRETS_FILE} (mode 600, owner communication)"
