#!/usr/bin/env bash
# render-toml-configs.sh — fill production.toml with realm + TURN URLs
# derived from the host's public IP (or operator-provided --domain).
#
# Mode-conditional: TURN URL port is 443 in HAProxy mode (SNI multiplexed)
# or 5349 when coturn binds the public TLS port directly.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

PROD_TOML="/opt/communication/apps/communication/config/production.toml"

# Discover IP and domains.
COMMUNICATION_IP="${COMMUNICATION_IP:-$(curl -fsS -4 --max-time 5 https://ifconfig.me 2>/dev/null || true)}"
if [[ -z "${COMMUNICATION_IP}" ]]; then
  die "Cannot determine public IP. Set COMMUNICATION_IP."
fi
ok "Public IP: ${COMMUNICATION_IP}"

DOMAIN="${COMMUNICATION_DOMAIN:-${COMMUNICATION_IP}.sslip.io}"
TURN_DOMAIN="turn-${COMMUNICATION_IP}.sslip.io"
ok "App domain: ${DOMAIN}"
ok "TURN domain: ${TURN_DOMAIN}"

EDGE_HAPROXY_ENABLED="${EDGE_HAPROXY_ENABLED:-true}"
if [[ "${EDGE_HAPROXY_ENABLED}" == "true" ]]; then
  TURN_TLS_PORT=443
else
  TURN_TLS_PORT=5349
fi
TURN_PLAIN_PORT=3478

# In HAProxy mode Fastify must bind 127.0.0.1:8443 (HAProxy backend
# target). In direct mode (--no-haproxy) Fastify itself owns :443.
if [[ "${EDGE_HAPROXY_ENABLED}" == "true" ]]; then
  FASTIFY_PORT=8443
  FASTIFY_HOST="127.0.0.1"
else
  FASTIFY_PORT=443
  FASTIFY_HOST="0.0.0.0"
fi

# CORS origins. Empty list crashes load-config in production; populate
# via the orchestrator's --cors-origin flag (repeatable, comma-list)
# or fall back to the GitHub Pages portfolio + localhost dev defaults.
COMMUNICATION_CORS_ORIGINS="${COMMUNICATION_CORS_ORIGINS:-https://frozik.github.io,http://localhost:5173}"
CORS_TOML_LIST=""
IFS=',' read -ra _origins <<< "${COMMUNICATION_CORS_ORIGINS}"
for origin in "${_origins[@]}"; do
  origin="${origin// /}"
  [[ -z "${origin}" ]] && continue
  if [[ -n "${CORS_TOML_LIST}" ]]; then
    CORS_TOML_LIST="${CORS_TOML_LIST}, "
  fi
  CORS_TOML_LIST="${CORS_TOML_LIST}\"${origin}\""
done

info "Rendering ${PROD_TOML}"
cat > "${PROD_TOML}" <<TOML
# Generated by render-toml-configs.sh — values overlaid on default.toml.

[server]
port = ${FASTIFY_PORT}
host = "${FASTIFY_HOST}"
cors_allowed_origins = [${CORS_TOML_LIST}]

[server.tls]
enabled = true
cert_path = "/etc/letsencrypt/live/communication/fullchain.pem"
key_path = "/etc/letsencrypt/live/communication/privkey.pem"

[edge]
haproxy_enabled = ${EDGE_HAPROXY_ENABLED}

[turn]
enabled = true
realm = "${TURN_DOMAIN}"
urls = [
  "stun:${TURN_DOMAIN}:${TURN_PLAIN_PORT}",
  "turn:${TURN_DOMAIN}:${TURN_PLAIN_PORT}?transport=udp",
  "turn:${TURN_DOMAIN}:${TURN_PLAIN_PORT}?transport=tcp",
  "turns:${TURN_DOMAIN}:${TURN_TLS_PORT}?transport=tcp"
]
TOML
chown communication:communication "${PROD_TOML}"
chmod 644 "${PROD_TOML}"
ok "Wrote ${PROD_TOML}"

# Persist computed values for downstream scripts.
mkdir -p /etc/communication
cat > /etc/communication/deploy-vars <<VARS
COMMUNICATION_IP=${COMMUNICATION_IP}
COMMUNICATION_DOMAIN=${DOMAIN}
TURN_DOMAIN=${TURN_DOMAIN}
EDGE_HAPROXY_ENABLED=${EDGE_HAPROXY_ENABLED}
TURN_TLS_PORT=${TURN_TLS_PORT}
TURN_PLAIN_PORT=${TURN_PLAIN_PORT}
FASTIFY_PORT=${FASTIFY_PORT}
FASTIFY_HOST=${FASTIFY_HOST}
VARS
chmod 644 /etc/communication/deploy-vars
ok "Persisted /etc/communication/deploy-vars"
